security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

    providers:
        users_in_memory:
            memory:
                users:
                    admin:
                        password: "$2y$10$4EBmYvtmOYkGwOyIlumi6uLgpU16GGUhXJQBUAxeEIv9kHMS0F75S"
                        roles: ["ROLE_ADMIN"]
                    user:
                        password: "$2y$10$.Y.qW2y8wlUjy3HGnOzMMuRGklsCtrEqZAJpWjISYjBh7kSvPx5q6"
                        roles: ["ROLE_USER"]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users_in_memory
            http_basic: ~
            logout:
                path: app_logout

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]

    access_control:
        - { path: ^/dashboard, roles: ROLE_USER }
